// Package manifest records which parser rules a binary shipped with, so
// a later comparison can tell a file the user edited from one that
// arrived in the release.
//
// The manifest is generated by build.sh and compiled into the binary with
// go:embed. That placement is the point: there is no installer, so
// nothing on disk records what a file looked like when it arrived. The
// running binary is the only thing that reliably knows what it shipped
// with, and it carries that knowledge wherever it is copied — which
// matters for a tool whose documented distribution method is copying the
// executable onto a share.
//
// Two consumers:
//
//   - `--verbose` reports rules that differ from shipped, which is the
//     first question worth asking when someone reports a format parsing
//     oddly.
//   - The self-update design in docs/SELF_UPDATE_PROPOSAL.md, which
//     replaces only rules that are byte-identical to what shipped. That
//     updater does not exist yet; the manifest has to start shipping
//     before it does, because an install whose binary carries no manifest
//     can never be reasoned about retroactively.
package manifest

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Manifest maps a parser rule's base filename to the hex SHA-256 it had
// when the binary was built.
type Manifest map[string]string

// State classifies one rule file against the manifest.
type State int

const (
	// Unchanged: present on disk and byte-identical to what shipped.
	Unchanged State = iota
	// Modified: shipped with the binary, since edited.
	Modified
	// Removed: shipped with the binary, since deleted. Deleting a rule
	// is how you disable it, so this is a deliberate act, not damage.
	Removed
	// Added: on disk but never shipped — the user's own rule.
	Added
)

func (s State) String() string {
	switch s {
	case Unchanged:
		return "unchanged"
	case Modified:
		return "modified"
	case Removed:
		return "removed"
	case Added:
		return "added"
	}
	return "unknown"
}

// Diff is the comparison of a rules directory against the manifest,
// with each slice sorted for stable output.
type Diff struct {
	Unchanged []string
	Modified  []string
	Removed   []string
	Added     []string
}

// Clean reports whether the directory matches what shipped exactly.
func (d Diff) Clean() bool {
	return len(d.Modified) == 0 && len(d.Removed) == 0 && len(d.Added) == 0
}

// Summary renders the differences on one line, or "" when clean. Suitable
// for a --verbose line; callers wanting detail should read the fields.
func (d Diff) Summary() string {
	var parts []string
	for _, p := range []struct {
		label string
		names []string
	}{
		{"modified", d.Modified},
		{"removed", d.Removed},
		{"added", d.Added},
	} {
		if len(p.names) > 0 {
			parts = append(parts, fmt.Sprintf("%d %s (%s)",
				len(p.names), p.label, strings.Join(p.names, ", ")))
		}
	}
	return strings.Join(parts, "; ")
}

// Parse reads the manifest format written by build.sh: one
// "<sha256>  <filename>" per line, with # comments and blank lines
// ignored. The shape matches sha256sum output so the file can be checked
// with standard tools.
func Parse(data []byte) (Manifest, error) {
	m := Manifest{}
	sc := bufio.NewScanner(bytes.NewReader(data))
	line := 0
	for sc.Scan() {
		line++
		text := strings.TrimSpace(sc.Text())
		if text == "" || strings.HasPrefix(text, "#") {
			continue
		}
		fields := strings.Fields(text)
		if len(fields) != 2 {
			return nil, fmt.Errorf("manifest line %d: want '<sha256>  <name>', got %q", line, text)
		}
		sum, name := fields[0], filepath.Base(fields[1])
		if len(sum) != 64 {
			return nil, fmt.Errorf("manifest line %d: %q is not a sha256", line, sum)
		}
		if _, err := hex.DecodeString(sum); err != nil {
			return nil, fmt.Errorf("manifest line %d: %q is not hex", line, sum)
		}
		m[name] = strings.ToLower(sum)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return m, nil
}

// Compare classifies every .yaml file in dir against the manifest.
//
// A missing or unreadable directory yields every manifest entry as
// Removed rather than an error — running without parsers.d/ is supported
// (NDJSON and EVTX need no rules), so it is a state to report, not a
// failure.
func (m Manifest) Compare(dir string) (Diff, error) {
	var d Diff

	onDisk := map[string]string{}
	entries, err := os.ReadDir(dir)
	if err != nil && !os.IsNotExist(err) {
		return d, fmt.Errorf("manifest: read %s: %w", dir, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if ext := strings.ToLower(filepath.Ext(name)); ext != ".yaml" && ext != ".yml" {
			continue
		}
		sum, err := hashFile(filepath.Join(dir, name))
		if err != nil {
			return d, err
		}
		onDisk[name] = sum
	}

	for name, want := range m {
		got, present := onDisk[name]
		switch {
		case !present:
			d.Removed = append(d.Removed, name)
		case got == want:
			d.Unchanged = append(d.Unchanged, name)
		default:
			d.Modified = append(d.Modified, name)
		}
	}
	for name := range onDisk {
		if _, shipped := m[name]; !shipped {
			d.Added = append(d.Added, name)
		}
	}

	for _, s := range []*[]string{&d.Unchanged, &d.Modified, &d.Removed, &d.Added} {
		sort.Strings(*s)
	}
	return d, nil
}

// Build hashes every rule file in dir, producing the manifest that
// build.sh writes. Kept here rather than in the shell script so the
// generator and the reader cannot drift apart, and so a test can assert
// the committed file is current.
func Build(dir string) (Manifest, error) {
	m := Manifest{}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("manifest: read %s: %w", dir, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if ext := strings.ToLower(filepath.Ext(name)); ext != ".yaml" && ext != ".yml" {
			continue
		}
		sum, err := hashFile(filepath.Join(dir, name))
		if err != nil {
			return nil, err
		}
		m[name] = sum
	}
	return m, nil
}

// Render writes the manifest in the on-disk format, sorted by name so the
// output is byte-stable across machines and regenerating it produces no
// spurious diff.
func (m Manifest) Render() []byte {
	names := make([]string, 0, len(m))
	for n := range m {
		names = append(names, n)
	}
	sort.Strings(names)

	var b bytes.Buffer
	b.WriteString("# obs-viewer parser rule manifest.\n")
	b.WriteString("# Generated by build.sh — do not edit.\n")
	b.WriteString("#\n")
	b.WriteString("# Records the SHA-256 of every parsers.d/ rule as shipped, so a\n")
	b.WriteString("# later comparison can tell an edited rule from an untouched one.\n")
	b.WriteString("#\n")
	b.WriteString("# Names are bare, so verify from inside the rules directory:\n")
	b.WriteString("#   (cd parsers.d && sha256sum -c ../parsers.d.sha256)\n")
	for _, n := range names {
		fmt.Fprintf(&b, "%s  %s\n", m[n], n)
	}
	return b.Bytes()
}

func hashFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("manifest: hash %s: %w", path, err)
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), nil
}
